{
 "title": "V2Ray Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(v2ray_up == 1)" }
   ]
  },
  {
   "title": "Real-Time Detail Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(v2ray_traffic_downlink_bytes_total[$__range])"
    },
    {
     "expr": "increase(v2ray_traffic_uplink_bytes_total[$__range])"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{dimension=\"inbound\"}[5m]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{dimension=\"inbound\"}[5m]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": " Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(v2ray_up) - count(v2ray_up == 1)"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Download shadowsocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{dimension=\"inbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload shadowsocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{dimension=\"inbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{dimension=\"outbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Outbounds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{dimension=\"outbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{dimension=\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{dimension=\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}